## oh-my-zsh
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="guinesis"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh


## ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

## Aliases file
source ~/.zsh_aliases

## Exports file
source ~/.zsh_exports

## Secret file
source ~/.secrets.zsh

# ssh-agent
# ---------
local ssh_agent_env="$HOME/.ssh/environment-$HOST"
function start_ssh_agent() {
	ssh-agent | sed 's/^echo/#echo/' > ${ssh_agent_env}
	chmod 600 ${ssh_agent_env}
	. ${ssh_agent_env} > /dev/null
	ssh-add $HOME/.ssh/*_rsa
}
if [ -f "${ssh_agent_env}" ]; then
	. ${ssh_agent_env} > /dev/null
	ps x | grep ${SSH_AGENT_PID} | grep ssh-agent > /dev/null || {
		start_ssh_agent;
	}
else
	start_ssh_agent;
fi
unfunction start_ssh_agent
unset ssh_agent_env

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
