## oh-my-zsh
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="guinesis"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh


## ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Aliases
#alias ls="gls --group-directories-first --color=auto"  # Installed with `brew install coreutils
alias l="ls -lh"
alias ne="nvim"
alias la="l -a"
alias pb="cd $HOME/phantombuster"
alias v="vim"
alias sudo="sudo "
alias brewski='brew update && brew upgrade && brew cleanup; brew prune; brew doctor;'
alias t="tmux source-file ~/.tmux.conf"
alias i3config="v ~/.config/i3/config"
alias zshconfig="v ~/.zshrc"
alias dotconfig="v ~/.dotfiles"
alias vlc="~/Applications/VLC.app/Contents/MacOS/VLC"

## Env
export EDITOR="/usr/bin/vim"
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export NODE_PATH="$HOME/.node/node_modules"
export PATH="$HOME/.node/bin:$PATH"

source ~/.secrets.zsh

# ssh-agent
# ---------
local ssh_agent_env="$HOME/.ssh/environment-$HOST"
function start_ssh_agent() {
	ssh-agent | sed 's/^echo/#echo/' > ${ssh_agent_env}
	chmod 600 ${ssh_agent_env}
	. ${ssh_agent_env} > /dev/null
	ssh-add $HOME/.ssh/*_rsa
}
if [ -f "${ssh_agent_env}" ]; then
	. ${ssh_agent_env} > /dev/null
	ps x | grep ${SSH_AGENT_PID} | grep ssh-agent > /dev/null || {
		start_ssh_agent;
	}
else
	start_ssh_agent;
fi
unfunction start_ssh_agent
unset ssh_agent_env

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

## Ruby
## ----
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile

if [ "$(uname 2> /dev/null)" = "Linux" ]; then
    setxkbmap -layout us -option ctrl:nocaps
    export MANPATH="/usr/local/man:$MANPATH"
    export LANG=en_US.UTF-8
    export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)
fi
